### ISSUE TITLE
Problems with "parse" during the installation of modtox

### ISSUE THREAD

**Issue by modeorru** [NostrumBioDiscovery/modtox#7] opened 2019-09-18 15:26 UTC
I got problems with the package "parse" since even though was installed couldn't run the program without getting "no module named parse". I think it has to be related with an incompatibility between python's versions (2.7 / 3). To solve this issue "manually", just rewrite few lines of different py-files in ../chembl_websource_client/ (e.g. replacing "from urllib.parse import urlparse" to "from urlparse import urlparse") so that could be executed with python2.7

**Comment by danielSoler93** [comment] 2019-09-18 17:29
Same as issue #5 ?

**Comment by danielSoler93** [comment] 2019-09-18 20:00
Duplicate of #5

**Closed by danielSoler93** 2019-09-18 20:00 UTC
